# Generated by Django 5.1 on 2024-09-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wish',
            field=models.BooleanField(default=False),
        ),
    ]
