# Generated by Django 5.1 on 2024-09-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='Customer_name',
            new_name='customer_name',
        ),
    ]
