# Generated by Django 5.1 on 2024-09-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_customer_name_orderrequest_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
