# Generated by Django 5.1 on 2024-09-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='have_dis',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='is_accept',
            field=models.BooleanField(default=True),
        ),
    ]
