# Generated by Django 5.1 on 2024-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_discount_product_have_dis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_and_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_slug', models.SlugField(max_length=100, unique=True)),
                ('write_comment', models.TextField(blank=True, max_length=1000)),
                ('user_name', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.FloatField(blank=True)),
            ],
        ),
    ]
