# Generated by Django 5.1 on 2024-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_comment_and_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_and_review',
            name='comment_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment_and_review',
            name='user_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment_and_review',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
