# Generated by Django 5.1 on 2024-10-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_comment_and_review_comment_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment_and_review',
            new_name='CommentAndReview',
        ),
    ]
