# Generated by Django 5.1 on 2024-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_comment_and_review_commentandreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentandreview',
            name='comment_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
