# Generated by Django 5.1 on 2024-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_commentandreview_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentandreview',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
