# Generated by Django 5.1 on 2024-10-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_commentandreview_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentandreview',
            name='user_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
