# Generated by Django 5.1 on 2024-10-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_commentandreview_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentandreview',
            name='avg_ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
