# Generated by Django 5.1 on 2024-10-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_commentandreview_specific_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specific_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commentandreview'),
        ),
    ]
