# Generated by Django 5.1 on 2024-08-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='picture',
            new_name='pro_picture',
        ),
    ]
