# Generated by Django 5.1 on 2024-09-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_picture_account_pro_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_product_name', models.CharField(max_length=100)),
                ('wish_product_price', models.IntegerField()),
                ('wish_product_image', models.ImageField(upload_to='')),
                ('wish_product_description', models.CharField(max_length=100)),
                ('wish_product_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
