# Generated by Django 5.1 on 2024-09-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wishlistproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
