# Generated by Django 5.1 on 2024-09-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wishlistproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistproduct',
            name='wish_product_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
