# Generated by Django 5.1 on 2024-09-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='find_product_name',
        ),
    ]
