# Generated by Django 5.1 on 2024-09-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_find_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='find_product_name',
            field=models.JSONField(default=list),
        ),
    ]
